//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpadmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblapplication
    {
        public int Applications_Id { get; set; }
        public Nullable<int> Registration_Id { get; set; }
        public string Name_Of_Trainee { get; set; }
        public string Qualification { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string Select_Training { get; set; }
        public Nullable<decimal> Totalfees { get; set; }
        public string Discount { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<decimal> Advance_Paid { get; set; }
        public Nullable<System.DateTime> On_Dated { get; set; }
        public Nullable<decimal> Remaining_Amount { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<bool> Active { get; set; }
        public string image { get; set; }
    }
}
